import { Montserrat } from "next/font/google";
import './../style/style.scss';


const main = Montserrat({ 
  subsets: ["latin"],
  variable: '--main-font',
  display: 'swap',
});

export const metadata = {
  title: "Setvice market",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${main.variable}`}>
        {children}
      </body>
    </html>
  );
}
